### ISSUE TITLE
This is cool

### ISSUE THREAD

**Issue by foopod** [ScreamingHawk/ava.standen.link#1]
This looks super cool. How did Ava do with the HTML? I often think students would find it easier to type something like Pug, but I am sure it would have downfalls too.

Have you tried Twine together? Or if you are looking for more programming maybe inkle (https://www.inklestudios.com/ink/) might be better.

Looking forward to more games from the two of you :D

**Comment by ScreamingHawk** [comment]
She narrates. I code :)

Most of the stuff is to teach her concepts, rather than getting her to do all the grunt work. 
Once she gets more proficient at typing we will swap it around. 

I like `pug` but think it's better to teach the pure languages where possible. `pug` will go out of fashion long before `HTML` and `JavaScript`.

**Comment by foopod** [comment]
That makes sense, most of our 10-12 yo students struggle to type out html. And yeah, it makes sense not to teach frameworks before core languages.

How do I see `the_fight`? Looks interesting..

And the more I see your domain name the cooler it gets.

**Comment by ScreamingHawk** [comment]
Added a landing page with links to the other pages. Should be easy to find content now. 

Don't view `the_fight` on mobile data. It's 66 photos. Lol

**Comment by ScreamingHawk** [comment]
:D Closing this
